Add additional clean up cron job for folder deletion in DB without corresponding folder in S3
it-at-m/digiwf-s3-integration pull request #19
Opened 2022-02-18 13:08 UTC by boal

close #16

2022-02-21 21:40 UTC, dominikhorn93 commented on README.md
> +``io.muenchendigital.digiwf.s3.cronjob.cleanup.database-folder-without-corresponding-s3-folder=0 15 10 16 * ?``
I would shorten the description. How about : 
io.muenchendigital.digiwf.s3.cronjob.cleanup.unused-folders

2022-02-21 21:42 UTC, dominikhorn93 commented on digiwf-s3-integration-starter/src/main/java/io/muenchendigital/digiwf/s3/integration/configuration/CronJobConfiguration.java
> +@ConditionalOnProperty(
How does it behave? Does this only apply when both settings are active? Should we possibly make 2 configurations out of it, if so?

2022-02-21 21:43 UTC, dominikhorn93 commented on digiwf-s3-integration/src/main/java/io/muenchendigital/digiwf/s3/integration/domain/service/cronjob/CleanUpDatabaseFolderWithoutCorrespondingS3Folder.java
> +        this.folderRepository.findAllByEndOfLifeIsNull()
What if we request a RefId and then don't upload a file for 10 minutes? If the cron job runs in the meantime, will the folder be deleted?

2022-02-21 21:44 UTC, dominikhorn93 requested changes
Have a couple of points we should discuss.

2022-02-22 07:29 UTC, boal commented on digiwf-s3-integration/src/main/java/io/muenchendigital/digiwf/s3/integration/domain/service/cronjob/CleanUpDatabaseFolderWithoutCorrespondingS3Folder.java
> +        this.folderRepository.findAllByEndOfLifeIsNull()
The folder entity within the database is only deleted if the creation of the entity was more than a month ago.

2022-02-22 07:30 UTC, boal commented on digiwf-s3-integration/src/main/java/io/muenchendigital/digiwf/s3/integration/domain/service/cronjob/CleanUpDatabaseFolderWithoutCorrespondingS3Folder.java
> +        this.folderRepository.findAllByEndOfLifeIsNull()
See method ```shouldDatabaseFolderBeDeleted``` in Line  43

2022-02-22 07:30 UTC, boal commented on digiwf-s3-integration/src/main/java/io/muenchendigital/digiwf/s3/integration/domain/service/cronjob/CleanUpDatabaseFolderWithoutCorrespondingS3Folder.java
> +        this.folderRepository.findAllByEndOfLifeIsNull()
See method shouldDatabaseFolderBeDeleted in Line 43

2022-02-22 07:34 UTC, boal commented on digiwf-s3-integration-starter/src/main/java/io/muenchendigital/digiwf/s3/integration/configuration/CronJobConfiguration.java
> +@ConditionalOnProperty(
Both clean up cron jobs are mandatory, because otherwise the S3-Folder and Database-Folder with metadata will get out of sync.

2022-02-22 07:56 UTC, boal commented on digiwf-s3-integration-starter/src/main/java/io/muenchendigital/digiwf/s3/integration/configuration/CronJobConfiguration.java
> +@ConditionalOnProperty(
According javadoc all values in "name" have to be set. See first sentence.

https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/condition/ConditionalOnProperty.html

2022-02-22 07:56 UTC, boal commented on README.md
> +``io.muenchendigital.digiwf.s3.cronjob.cleanup.database-folder-without-corresponding-s3-folder=0 15 10 16 * ?``
good point

2022-02-22 10:39 UTC, boal commented on README.md
> +``io.muenchendigital.digiwf.s3.cronjob.cleanup.database-folder-without-corresponding-s3-folder=0 15 10 16 * ?``
Property changed to ```unused-folders```.

2022-02-22 10:42 UTC, dominikhorn93 commented on digiwf-s3-integration/src/main/java/io/muenchendigital/digiwf/s3/integration/domain/service/cronjob/CleanUpDatabaseFolderWithoutCorrespondingS3Folder.java
> +        this.folderRepository.findAllByEndOfLifeIsNull()
You are right... didn't see that 👍

2022-02-22 10:44 UTC, dominikhorn93 commented on digiwf-s3-integration-starter/src/main/java/io/muenchendigital/digiwf/s3/integration/configuration/CronJobConfiguration.java
> +@ConditionalOnProperty(
Ok, makes sense to me. I also don't see a use case right now where we need one property but not the other. If it comes to that, we can still outsource this into 2 configurations

2022-02-22 10:44 UTC, dominikhorn93 approved these changes

2022-02-22 10:51 UTC, merged